### ISSUE TITLE
Cannot establish connection with PC

### ISSUE THREAD

**Issue by rafacpitta** [souvik1997/obdython#5]
Hi, I'm trying to connect the OBDII to my PC using bluetooth. I tried the obdython since I can't connect anyway with it, so everything I find I try. My OBDII connector works, since I can use it with some apps at my Android.
`>python recorder.py -d bluetooth -m 00:0D:18:A0:4E:35 -c 1 -r rpm load -o out.csv
`
`Traceback (most recent call last):`
`File "recorder.py", line 68, in <module>`
`main()`
`File "recorder.py", line 39, in main`
`port.connect()`
`  File "build\bdist.win-amd64\egg\obdython\__init__.py", line 46, in connect`
`  File "build\bdist.win-amd64\egg\obdython\__init__.py", line 160, in ready`
`  File "build\bdist.win-amd64\egg\obdython\__init__.py", line 274, in read`
`  File "C:\ProgramData\Anaconda2\lib\site-packages\bluetooth\msbt.py", line 78, in recv
    return bt.recv (self._sockfd, numbytes)`
`IOError: A non-blocking socket operation could not be completed immediately.`

Is this something to the setblocking to True?

**Comment by rafacpitta** [comment]
I realized I needed to simulate a serial port for this kind of connection, like:

```
sudo rfcomm release all
sudo rfcomm bind rfcomm1 00:0D:18:A0:4E:35
```
